Vagrant.configure("2") do |config|
  config.vm.provider :vmware_desktop do |v|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "1"
    v.vmx["scsi0:0.virtualdisk.useshared"] = "FALSE"
  end
end
